<a href="https://colab.research.google.com/github/sakshitiwari1234/SKLEARN_PYTHON/blob/main/Feature_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is feature scaling

feature scaling is a data preprocessing technique used to transform the value of features or variables in a dataset to a similar scale.

The purpose is to ensure that all features constribute equally to the model and to avoid the domination of features with larger values.

####  there are two types of scaling measurement used in scikit-learn.

1. Normalization.
2. Standardization.

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/content/CAR DETAILS FROM CAR DEKHO.csv")

In [3]:
data

name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
0     Petrol  Individual       Manual   First Owner  
1     Petrol  Individual       Manual   First Owner  
2     Diesel  Individual       Manual   First Owner  
3     Petrol  Individual       Manual   First Owner  
4     Diesel  Individual       Manual  Second Owner  
...      ...         ...          ...           ...  
4335  Diesel  Individual       Manual  Second Owner  
4336  Diesel  Individual       Manual  Second Owner  
4337  Petrol  Individual       Manual  Second Owner  
4338  Diesel  Individual       Manual   First Owner  
4339  Petrol  Individual       Manual   First Owner  

[4340 rows x 8 columns]

In this dataset we have selling price as the output variable , it is a column. so remeber that output variable whose values apparently increases is used in regression model.

We are taking three 'selling price', 'year', 'km driven' , these numerical columns for calculations which will be helpful for furthur process.

In [5]:
data = data[['selling_price', 'year', 'km_driven']]

In [6]:
data.head(2)

selling_price  year  km_driven
0          60000  2007      70000
1         135000  2007      50000

Feature scaling is a technique in which the features of dataset are converted into similar scale.
It is done by two types - 1. Normalization , 2. Standardization.

In [7]:
data2 = pd.read_csv("/content/Book1.csv")

In [8]:
data2

Student   CGPA  Salary
0         1   3.0      60
1         2   3.0      40
2         3   4.0      40
3         4   4.5      50
4         5   4.2      52

If we train any model on this dataset , therefore mostly models will dominate on salary column.
Therefore , we scale all the columns to a same level by normalization technique.



We use min-max scaling , wht is it ? let know.

Normlaiation is a technique in which values are shifted are rescaled so that they range between 0 and 1. This process which bring data in range of 0 and 1 is called as Min-Max scaling.

IMPORTANT - the result of min-max scaling on performing normalization on dataset input-features is only between 0 and 1. The formula is:-


In [9]:
data.head(1)

selling_price  year  km_driven
0          60000  2007      70000

#### Appplying Normlaization : Min-Max Scaling

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
scaler = MinMaxScaler()

In [12]:
scaled_df= scaler.fit_transform(data)

In [13]:
scaled_df

array([[0.0045045 , 0.53571429, 0.08678301],
       [0.01295045, 0.53571429, 0.06198751],
       [0.06531532, 0.71428571, 0.12397626],
       ...,
       [0.01013514, 0.60714286, 0.10290008],
       [0.09515766, 0.85714286, 0.11157851],
       [0.02308559, 0.85714286, 0.04958976]])

In [15]:
# Converting this numpy arrays into dataframe.
scaled_df = pd.DataFrame(data = scaled_df, columns = data.columns)

In [16]:
scaled_df

selling_price      year  km_driven
0          0.004505  0.535714   0.086783
1          0.012950  0.535714   0.061988
2          0.065315  0.714286   0.123976
3          0.025901  0.892857   0.057028
4          0.048423  0.785714   0.174807
...             ...       ...        ...
4335       0.043919  0.785714   0.099181
4336       0.043919  0.785714   0.099181
4337       0.010135  0.607143   0.102900
4338       0.095158  0.857143   0.111579
4339       0.023086  0.857143   0.049590

[4340 rows x 3 columns]

The scaling is always done after the train test splitting of the data.


Performing the scaling once again with same data.

In [17]:
data

selling_price  year  km_driven
0             60000  2007      70000
1            135000  2007      50000
2            600000  2012     100000
3            250000  2017      46000
4            450000  2014     141000
...             ...   ...        ...
4335         409999  2014      80000
4336         409999  2014      80000
4337         110000  2009      83000
4338         865000  2016      90000
4339         225000  2016      40000

[4340 rows x 3 columns]

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X = data.drop('selling_price', axis = 1)

In [25]:
Y=data['selling_price']

In [22]:
X

year  km_driven
0     2007      70000
1     2007      50000
2     2012     100000
3     2017      46000
4     2014     141000
...    ...        ...
4335  2014      80000
4336  2014      80000
4337  2009      83000
4338  2016      90000
4339  2016      40000

[4340 rows x 2 columns]

In [26]:
Y

0        60000
1       135000
2       600000
3       250000
4       450000
         ...  
4335    409999
4336    409999
4337    110000
4338    865000
4339    225000
Name: selling_price, Length: 4340, dtype: int64

In [28]:
xtrain, xtest, ytrain, ytest = train_test_split(X,Y, test_size = 0.2, random_state =42 )

In [29]:
xtrain

year  km_driven
227   2017      20000
964   2018      50000
2045  2013      25000
1025  2011      70000
4242  2017      72000
...    ...        ...
3444  2006      50000
466   2011      80000
3092  2016      51000
3772  2013      80000
860   2013      80000

[3472 rows x 2 columns]

In [33]:
xtest.shape

(868, 2)

In [34]:
ytrain.shape

(3472,)

In [35]:
ytest.shape

(868,)

In [36]:
X_train_scaled = scaler.fit_transform(xtrain)
X_test_scaled = scaler.fit_transform(xtest)

In [37]:
X_train_scaled

array([[0.89285714, 0.02479426],
       [0.92857143, 0.06198751],
       [0.75      , 0.03099313],
       ...,
       [0.85714286, 0.06322728],
       [0.75      , 0.09918076],
       [0.75      , 0.09918076]])

In [38]:
X_test_scaled

array([[0.58333333, 0.22636103],
       [0.95833333, 0.07449857],
       [0.5       , 0.11668481],
       ...,
       [0.625     , 0.11174785],
       [0.875     , 0.01570201],
       [0.95833333, 0.08309456]])

In [39]:
X_train_scaled = pd.DataFrame(data = X_train_scaled, columns = xtrain.columns)

In [41]:
X_test_scaled = pd.DataFrame(data = X_test_scaled , columns = xtest.columns)

In [42]:
X_train_scaled

year  km_driven
0     0.892857   0.024794
1     0.928571   0.061988
2     0.750000   0.030993
3     0.678571   0.086783
4     0.892857   0.089263
...        ...        ...
3467  0.500000   0.061988
3468  0.678571   0.099181
3469  0.857143   0.063227
3470  0.750000   0.099181
3471  0.750000   0.099181

[3472 rows x 2 columns]

In [44]:
X_test_scaled

year  km_driven
0    0.583333   0.226361
1    0.958333   0.074499
2    0.500000   0.116685
3    0.750000   0.401146
4    0.833333   0.169054
..        ...        ...
863  0.458333   0.169054
864  0.791667   0.340974
865  0.625000   0.111748
866  0.875000   0.015702
867  0.958333   0.083095

[868 rows x 2 columns]

### When to apply minmax scaling ?

it is used in k nearest neighbours , SVM , K means clustering , PCA , Gradeitn based algorithm , and guassian mizture models.

in these algorithms , there is usage of distance based features , on which pre-processing techniques aree important to apply.