<a href="https://colab.research.google.com/github/sakshitiwari1234/SKLEARN_PYTHON/blob/main/Label_Encoder_AND_Ordinal_Encoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd


In [7]:
df = pd.read_csv("/content/label_Ordinal_encoder_sklearn_tutorial_3___.csv")

In [8]:
df

Unnamed: 0    fuel seller_type transmission        owner
0           0  petrol  individual       manual  first owner
1           1  petrol  individual       manual  first owner
2           2  diesel  individual       manual  first owner
3           3  diesel  individual       manual  first owner
4           4  diesel  individual       manual  first owner

### Data can be divided into two categories -

numerical data and categorical data.
when the data given , is in form of numbers it is called as numerical data, whereas data in form of categories division it is called as categorical data.

In this lecture, we are studying the library - scikit-learn in which we study about various techniques and process to handle the data while data modelling which are requirred to build and transform a machine learning model.

this lecture holds about the label and ordinal encode in scikitlearn library.

label order is the naming which we give , and ordinal order in the way we do classify data in some order accordingly.

so , look we are given different columns , in this the fuel column is the target column which will tell us that wheterh a particular car named is petrol fueled and diesel fueled.

Therefore , in order to make the machine work in proper way , we use categorical tranformation of data by assigning  the same category names a particular sort of numbers.

categories are of two types - nominal ordinal extc.


### using python

In [9]:
df


Unnamed: 0    fuel seller_type transmission        owner
0           0  petrol  individual       manual  first owner
1           1  petrol  individual       manual  first owner
2           2  diesel  individual       manual  first owner
3           3  diesel  individual       manual  first owner
4           4  diesel  individual       manual  first owner

In [10]:
df['transmission'].value_counts()

transmission
manual    5
Name: count, dtype: int64

In [45]:
df['transmission'] = df['transmission'].map({'manual': 0})

In [15]:
df

Unnamed: 0    fuel seller_type transmission        owner  0
0           0  petrol  individual       manual  first owner  0
1           1  petrol  individual       manual  first owner  0
2           2  diesel  individual       manual  first owner  0
3           3  diesel  individual       manual  first owner  0
4           4  diesel  individual       manual  first owner  0

In [46]:
df['seller_type'].value_counts()

seller_type
0    5
Name: count, dtype: int64

In [47]:
df['seller_type'] = df['seller_type'].map({'individual': 0})

In [48]:
df

Unnamed: 0    fuel  seller_type  transmission        owner  0  seller_new  \
0           0  petrol          NaN             0  first owner  0           0   
1           1  petrol          NaN             0  first owner  0           0   
2           2  diesel          NaN             0  first owner  0           0   
3           3  diesel          NaN             0  first owner  0           0   
4           4  diesel          NaN             0  first owner  0           0   

   trans_new  
0          0  
1          0  
2          0  
3          0  
4          0

In [49]:
df.sample(5)

Unnamed: 0    fuel  seller_type  transmission        owner  0  seller_new  \
3           3  diesel          NaN             0  first owner  0           0   
2           2  diesel          NaN             0  first owner  0           0   
0           0  petrol          NaN             0  first owner  0           0   
4           4  diesel          NaN             0  first owner  0           0   
1           1  petrol          NaN             0  first owner  0           0   

   trans_new  
3          0  
2          0  
0          0  
4          0  
1          0

In [50]:
df

Unnamed: 0    fuel  seller_type  transmission        owner  0  seller_new  \
0           0  petrol          NaN             0  first owner  0           0   
1           1  petrol          NaN             0  first owner  0           0   
2           2  diesel          NaN             0  first owner  0           0   
3           3  diesel          NaN             0  first owner  0           0   
4           4  diesel          NaN             0  first owner  0           0   

   trans_new  
0          0  
1          0  
2          0  
3          0  
4          0

Appplying label encoder.

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
xtrain , xtest , ytrain , ytest = train_test_split(df.drop('fuel', axis=1), df['fuel'], test_size = 0.2)

In [53]:
xtrain

Unnamed: 0  seller_type  transmission        owner  0  seller_new  \
1           1          NaN             0  first owner  0           0   
4           4          NaN             0  first owner  0           0   
0           0          NaN             0  first owner  0           0   
3           3          NaN             0  first owner  0           0   

   trans_new  
1          0  
4          0  
0          0  
3          0

In [54]:
ytrain

1    petrol
4    diesel
0    petrol
3    diesel
Name: fuel, dtype: object

In [55]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [56]:
le = LabelEncoder()

// target variable and predicted variables only uses labelencoder always remeber this.

In [57]:
le = LabelEncoder()


In [58]:
y_train_scaled = le.fit_transform(ytrain)

In [59]:
y_test_scaled = le.transform(ytest)

In [60]:
y_train_scaled

array([1, 0, 1, 0])

In [61]:
y_train_scaled

array([1, 0, 1, 0])

In [62]:
y_test_scaled

array([0])

labelEncoder is always used for the targeting and predicted variables / columns.

ordinal encoder is always used for the dependent variables or columns.

In [63]:
oe  =OrdinalEncoder()

In [64]:
xtrain = oe.fit_transform(xtrain)
# xtest = oe.transform(xtest)

TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.